name: Build readme on pull request opened

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Verify author
        run: |
          if [ "${{ github.event.pull_request.user.login }}" != "roveroniandrea" ]; then
            echo "PR author is not roveroniandrea. Skipping merge."
            exit 0
          fi
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies
        run: npm ci
      - name: Execute npm script
        run: npm run readme
      - name: Commit changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update README"
          git push
