name: Build readme on push to master

on:
  push:
    branches:
      - master

jobs:
  run-npm-script-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run npm script readme
        run: npm run readme
