name: Build readme on push to develop

on:
  push:
    branches:
      - develop

jobs:
  run-npm-script-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run npm script readme
        run: npm run readme
      - name: Merge to main
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git fetch
          git checkout main
          git merge develop
          git push origin main
