name: Build readme on push to develop

on:
  push:
    branches:
      - develop

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Merge develop into main
        run: |
          git fetch
          git checkout develop
          git merge main
          git checkout main
          git merge develop
          git push
      - name: Install dependencies
        run: npm ci
      - name: Execute npm script
        run: npm run readme
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Updated README'
          add: '.'
